import type { Definition, Kind, Point } from './types';
export const RULESET_ID = '3.0-2026-09-18';
/** Numeric combat parameters shared by resolution and read-only AI estimates. */
export const COMBAT_RULES = {
  sacrificeMaxHpCost: 20,
  sageAuraAttack: 5,
  slayerReflectRate: 0.5,
  archmageCounterChance: 2 / 3,
  archmageCounterHealth: 15,
  firelord: { radius: 6, damage: 80, splash: 10 },
  charger: { heavyChance: 1 / 12, criticalChance: 1 / 3, heavyBonus: 60, bonus: 20 },
  superCritical: { lethalChance: 1 / 5, doubleChance: 1 / 3, lethalDamage: 100 },
  vampire: { base: 0.2, perKill: 0.2 },
  minerBaseDamage: 10,
  frontDamageCap: 10,
  kingAttackImmunity: 10,
  catapultMarkDamage: 5,
  accumulator: { attack: 5, range: 1, max: 4 },
  giantAreaDamage: 15,
  goldSpellChance: 1 / 5,
  littleGoldImmunity: 1 / 2,
} as const;
/** Single source for both rule stats and the UI codex. Fractional attributes retain their exact numeric value. */
export const CATALOG: Definition[] = [
  {
    id: 1,
    tier: 'normal',
    name: '冲锋怪',
    glyph: '冲',
    role: '爆发',
    attack: 20,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '普通攻击：2/3概率造成20伤害，1/4概率造成40伤害，1/12概率造成80伤害。部署时可失去10点当前与最大生命，获得冲锋，当回合即可行动。',
  },
  {
    id: 2,
    tier: 'normal',
    name: '奶妈',
    glyph: '愈',
    role: '治疗',
    attack: 20,
    health: 30,
    range: 2,
    actions: 1,
    move: 1,
    description:
      '攻击友方随从时改为治疗20点，不超过生命上限。死亡后，由所属玩家选择一次无视距离的攻击或治疗；也可以放弃。',
  },
  {
    id: 3,
    tier: 'normal',
    name: '名刀',
    glyph: '佑',
    role: '守护',
    attack: 0,
    health: 60,
    range: 6,
    actions: 0,
    move: 0.5,
    description:
      '抽到时1/3为名刀，否则为破碎名刀。范围内友方（含自身）各获得一次与本名刀绑定的致命伤害保护，触发后以1血存活。多个名刀按入场顺序独立结算；来源离场、失效或超出范围时，不再提供保护，重新进入范围不会补回已用次数。攻击次数为0不妨碍移动：选择蓄力回合后，下一回合可消耗1层移动一格。',
  },
  {
    id: '3p',
    tier: 'derived',
    name: '破碎名刀',
    glyph: '影',
    role: '异变',
    attack: 40,
    health: 25,
    range: 1,
    actions: 1,
    move: 1,
    description:
      '攻击力=max(0,40−5n)，射程=n。n为以自身为中心3×3区域内的随从数量，包含双方、自身与衍生物；大体型只计一个。',
  },
  {
    id: 4,
    tier: 'normal',
    name: '定炮',
    glyph: '炮',
    role: '重炮',
    attack: 100,
    health: 40,
    range: 4,
    actions: 0.3333333333333333,
    move: 1,
    description:
      '不能直接攻击。主动选择蓄力作为本回合操作；回合开始已有至少2层时可攻击，开炮消耗全部层数。5层开炮射程+1；移动保留蓄力，移动回合不会自动增加层数。',
  },
  {
    id: 5,
    tier: 'normal',
    name: '大肉比',
    glyph: '岳',
    role: '重装',
    attack: 10,
    health: 111,
    range: 2,
    actions: 1,
    move: 0.5,
    description:
      '占2×2格。选择移动蓄力后，下一回合可消耗1层整体移动一格。技能：对体型外围一圈12格（含四个对角）内的目标造成15伤害，包含友方，每单位只结算一次。不能被策反。',
    skill: '震地',
    size: 2,
  },
  {
    id: 6,
    tier: 'normal',
    name: 'BUFF怪',
    glyph: '振',
    role: '辅助',
    attack: 20,
    health: 20,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '技能使当前攻击范围内的所有友方随从在下个己方回合攻击+10，对投石机无效；不同施放可以叠加。',
    skill: '鼓舞',
  },
  {
    id: 7,
    tier: 'normal',
    name: '钩子',
    glyph: '钩',
    role: '控制',
    attack: 30,
    health: 55,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '选择射程内的敌方随从，将其移到你的射程内另一合法空位。不能钩基地；大体型须完整放得下。',
    skill: '牵引',
  },
  {
    id: 8,
    tier: 'normal',
    name: '爆弹',
    glyph: '爆',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '选择一个完整2×2区域，对其中所有目标造成20伤害，包括双方随从与基地。每个大体型随从只受伤一次。',
    spell: 4,
  },
  {
    id: 9,
    tier: 'normal',
    name: '射手',
    glyph: '弓',
    role: '连击',
    attack: 10,
    health: 45,
    range: 5,
    actions: 2,
    move: 1,
    description: '选择攻击操作后可攻击两次，目标必须不同。不能把第二次攻击改为移动或技能。',
  },
  {
    id: 10,
    tier: 'normal',
    name: '投石机',
    glyph: '印',
    role: '标记',
    attack: 0,
    health: 20,
    range: 100,
    actions: 2,
    move: 1,
    description:
      '不能装备武器，不能接受友方单位提供的攻击力增益。命中敌方目标后施加一轮标记。目标满血时立即触发，或再次被同阵营的非投石机随从命中时触发，额外造成5伤害。同阵营标记可叠加，同一投石机重复命中也叠加；触发时逐层造成5伤害并全部移除。基地也使用同样的标记规则。',
  },
  {
    id: 11,
    tier: 'normal',
    name: '白嫖怪',
    glyph: '召',
    role: '遗赠',
    attack: 20,
    health: 20,
    range: 4,
    actions: 1,
    move: 1,
    description: '死亡后，下个己方回合额外召唤一次；多个白嫖怪的效果可累加。',
  },
  {
    id: 12,
    tier: 'normal',
    name: '跑得快',
    glyph: '疾',
    role: '游击',
    attack: 5,
    health: 1,
    range: 6,
    actions: 2,
    move: 2,
    description:
      '与敌方随从四向相邻时，攻击次数与移动距离各−1。攻击模式不可改为移动模式。死亡后在原地留下0/70/0/0/0的己方墓地。',
  },
  {
    id: 13,
    tier: 'normal',
    name: '直行侠',
    glyph: '驰',
    role: '突进',
    attack: 25,
    health: 35,
    range: 4,
    actions: 1,
    move: 3,
    description: '移动必须恰好三格，且只能沿同一行或同一列直线前进，途中不能穿过任何单位或基地。',
  },
  {
    id: 14,
    tier: 'normal',
    name: '献祭炮',
    glyph: '祭',
    role: '献祭',
    attack: 5,
    health: 65,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '自身生命上限−20，当前生命不超过新上限。消灭范围内另一友方随从，再选择一列，沿进攻方向对射程内该列第一个敌方造成被献祭者的当前攻击力伤害。献祭另一枚献祭炮时，额外获得一次仅本回合可用的召唤机会，可付2人头升级为终极召唤；即使没有可射击的敌人，也可直接献祭同类换取召唤。',
    skill: '献祭射击',
  },
  {
    id: 15,
    tier: 'normal',
    name: '蓄力怪',
    glyph: '炼',
    role: '成长',
    attack: 15,
    health: 35,
    range: 2,
    actions: 2,
    move: 1,
    description:
      '每次主动蓄力同时获得+5攻击与+1射程，最多4层。蓄力占本回合操作；移动保留蓄力，发动一次攻击后全部清空（即使伤害被免疫）。第四属性2代表每回合可攻击两次，第二次使用清空后的数值。',
    skill: '蓄力',
  },
  {
    id: 16,
    tier: 'normal',
    name: '伤害转化器',
    glyph: '镜',
    role: '转化',
    attack: 5,
    health: 100,
    range: 2,
    actions: 1,
    move: 1,
    description:
      '可被友方随从攻击。实际受到友方伤害后，可选择射程内一个敌方目标造成等量伤害；也可放弃。过量伤害只按实际扣血计。',
  },
  {
    id: 17,
    tier: 'normal',
    name: '金身',
    glyph: '御',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '抽到17时只有1/5概率获得金身，否则变为小金耶。使一个友方直到其下回合开始免疫所有伤害与所有敌方技能、法术，包括死吧！和策反。己方献祭等非伤害效果不受阻止。',
    spell: 100,
  },
  {
    id: '17p',
    tier: 'derived',
    name: '小金耶',
    glyph: '耶',
    role: '防御',
    attack: 10,
    health: 25,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '抽到17时4/5概率变为小金耶。每次将受到正数伤害时独立判定，50%概率免疫该次伤害；沉默后失效。不会免疫非伤害的处决、献祭或策反。',
  },
  {
    id: 18,
    tier: 'normal',
    name: '死吧！',
    glyph: '灭',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '施放当回合无效；使一友方在下个实际己方回合命中的首个敌方随从立即死亡，绕过所有名刀保护。不能处决基地；金身可免疫。冲锋号令不能提前生效，效果在该己方回合结束后失效。',
    spell: 7,
  },
  {
    id: 19,
    tier: 'normal',
    name: '路障小法师',
    glyph: '障',
    role: '召唤',
    attack: 20,
    health: 30,
    range: 4,
    actions: 1,
    move: 1,
    description: '在攻击范围内的合法空位生成0/50/0/0/0的己方路障。路障于你下个回合开始消失。',
    skill: '制造路障',
    mage: true,
  },
  {
    id: 20,
    tier: 'normal',
    name: '超级跑得快',
    glyph: '迅',
    role: '反击',
    attack: 20,
    health: 20,
    range: 2,
    actions: 2,
    move: 2,
    description:
      '20/20/2/2/2。死亡判定：1/2概率敌方不能获得这颗人头；否则对伤害来源造成30伤害。无随从伤害来源时不会虚构反击目标。',
  },
  {
    id: 21,
    tier: 'normal',
    name: '神行千里',
    glyph: '跃',
    role: '蓄势',
    attack: 30,
    health: 35,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '主动选择技能蓄力，在两个回合各积累1层；第三回合可扣10血，移动最多6格并攻击一次。移动不清除蓄力；发动需至少保留1血。',
    skill: '神行突袭',
  },
  {
    id: 22,
    tier: 'normal',
    name: '策反',
    glyph: '易',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '施放当回合无效；使一友方在下个实际己方回合首次以攻击本身对敌方随从造成正伤害时，将存活目标变为友方。零伤害或被免伤不触发、不消耗策反；投石标记爆炸不计作攻击本身的伤害。金身免疫；大肉比不能被策反，基地也不能被策反。新友方本回合疲劳，下一个己方回合即可行动（独行侠也不额外多休息）。冲锋号令不能提前生效；未触发的策反在该己方回合结束后失效。',
    spell: 3,
  },
  {
    id: 23,
    tier: 'normal',
    name: '独行侠',
    glyph: '孤',
    role: '爆发',
    attack: 5,
    health: 30,
    range: 5,
    actions: 6,
    move: 1,
    description:
      '部署回合及下一个己方回合休眠，从下下个己方回合起每回合正常行动。选择攻击可攻击6次，但不能混用移动。周围八格不可部署或移动友方。',
  },
  {
    id: 24,
    tier: 'normal',
    name: '厚脸皮',
    glyph: '盾',
    role: '防御',
    attack: 10,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '从正面进入的攻击伤害单次最多10。正面指攻击路径最后一步朝向自己的基地。可选择射程内不同命中方向的合法路径，允许绕路从侧面击中。未指定方向的命令沿用最短路径、并列优先正面的默认值。无方向法术与反伤不受此限制。',
  },
  {
    id: 25,
    tier: 'normal',
    name: '重铸',
    glyph: '铸',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '立即额外召唤一次；或消灭两个当前生命不少于各自一半生命上限的友方随从，额外召唤两次。新随从仍必须当回合部署。',
    spell: 7,
  },
  {
    id: 26,
    tier: 'normal',
    name: '杀手',
    glyph: '刃',
    role: '收割',
    attack: 20,
    health: 45,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '每击杀一个敌方随从依次升级：①生命上限+10并治疗10；②攻击+5；③射程+1；然后循环。包括敌方墓地与路障。',
  },
  {
    id: 'grave',
    tier: 'derived',
    name: '墓地',
    glyph: '冢',
    role: '衍生物',
    attack: 0,
    health: 70,
    range: 0,
    actions: 0,
    move: 0,
    description: '跑得快的死亡遗留物。可被攻击、治疗、献祭、策反，也参与行控制权与残影人数计算。',
  },
  {
    id: 'wall',
    tier: 'derived',
    name: '路障',
    glyph: '垒',
    role: '衍生物',
    attack: 0,
    health: 50,
    range: 0,
    actions: 0,
    move: 0,
    description: '路障小法师创造的临时单位，在召唤者的下个己方回合开始消失。',
  },
  {
    id: 'u1',
    tier: 'ultimate',
    name: '末日守卫',
    glyph: '劫',
    role: '终极随从',
    attack: 30,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '自带冲锋。普通攻击1/3概率伤害翻倍，1/5概率伤害为100；采用互斥区间，余下7/15为普通伤害。',
  },
  {
    id: 'u2',
    tier: 'ultimate',
    name: '超级蓄力怪',
    glyph: '蓄',
    role: '终极随从',
    attack: 15,
    health: 65,
    range: 4,
    actions: 1,
    move: 1,
    description: '可选择攻击蓄力，每层+15攻击，最多4层。移动不消耗层数；一次攻击后清空蓄力。',
  },
  {
    id: 'u3',
    tier: 'ultimate',
    name: '法术反制小法师',
    glyph: '断',
    role: '终极随从',
    attack: 30,
    health: 30,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '对手释放法术时，每个未被沉默、未被冻结的反制小法师独立进行1/3反制判定，成功则法术无效但消耗法术牌。按文档的法师名单，本棋子不属于寒冰法杖适用的法师。',
  },
  {
    id: 'u4',
    tier: 'ultimate',
    name: '破法者',
    glyph: '禁',
    role: '终极随从',
    attack: 10,
    health: 50,
    range: 4,
    actions: 1,
    move: 2,
    description:
      '攻击命中敌方随从后，使其眩晕一回合并永久移除原有描述、被动与技能（沉默）。基础五项数值和装备保留；金身或免疫塔可拦截负面技能。',
  },
  {
    id: 'u5',
    tier: 'ultimate',
    name: '寒冰法杖',
    glyph: '冰',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '法师专用，装备后射程+1。攻击命中敌方随从后冰冻两回合：不能行动，每回合结束扣5血，对双方视作中立，双方攻击都被其阻挡也都能攻击它。法师名单：普通19，终极6、13、14、19、20。',
    weapon: 15,
  },
  {
    id: 'u6',
    tier: 'ultimate',
    name: '大法师',
    glyph: '法',
    role: '终极随从',
    attack: 0,
    health: 45,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '攻击附加持续6回合的灼烧，每回合结束扣5血；装备寒冰法杖后不再灼烧，基础攻击改为10。技能先蓄力一回合，后续可在自身11×11区域选择行列交点，十字各20伤害、中心40，整局只可发动一次。',
    skill: '十字浩劫',
    mage: true,
  },
  {
    id: 'u7',
    tier: 'ultimate',
    name: '超级BW',
    glyph: '岳',
    role: '终极随从',
    attack: 20,
    health: 90,
    range: 3,
    actions: 1,
    move: 0.5,
    description:
      '占2×2格，半速移动须蓄力。每生一次免费能力：自身攻击与当前生命各−10，使另一友方生命上限/当前生命+5并变为2×2。必须有完整合法落位。',
    skill: '巨大化',
    size: 2,
  },
  {
    id: 'u8',
    tier: 'ultimate',
    name: '精英杀手',
    glyph: '噬',
    role: '终极随从',
    attack: 10,
    health: 50,
    range: 4,
    actions: 2,
    move: 2,
    description:
      '20%吸血，攻击20%概率暴击×2。每击杀敌方吸血率与暴击率各+20%；暴击率最多100%，吸血率可超过100%。第五次击杀时射程+1（仅一次）。',
  },
  {
    id: 'u9',
    tier: 'ultimate',
    name: '烈焰风暴',
    glyph: '焰',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '选择任一完整横排或竖排，立即对所有目标造成20伤害；下个己方回合开始对同一行/列再造成20伤害，按当时占位重新判定。',
    spell: 6,
  },
  {
    id: 'u10',
    tier: 'ultimate',
    name: '厚脸皮暴怒者',
    glyph: '怒',
    role: '终极随从',
    attack: 5,
    health: 110,
    range: 4,
    actions: 1,
    move: 1,
    description: '每实际受到一次任意来源的正数伤害，永久+15攻击。免疫伤害不触发。',
  },
  {
    id: 'u11',
    tier: 'ultimate',
    name: '弑君',
    glyph: '弑',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '装备者+5攻击、+25生命上限（不立即治疗）。每个己方回合第一次攻击造成的实际伤害获得100%吸血。',
    weapon: 8,
  },
  {
    id: 'u12',
    tier: 'ultimate',
    name: 'SZF',
    glyph: '弹',
    role: '终极随从',
    attack: 0,
    health: 80,
    range: 0,
    actions: 0,
    move: 2.5,
    description:
      '抽到时1/10合成成功，否则为小BW。冲锋。先蓄力一回合，下回合可移动5次、每次四向1格。进入敌方/基地格造成30伤害后，必须选择方向弹出1格；若继续碰敌方则再伤害并继续弹出，弹出不消耗移动次数。',
  },
  {
    id: 'u12p',
    tier: 'derived',
    name: '小BW',
    glyph: '滚',
    role: '终极随从',
    attack: 0,
    health: 100,
    range: 0,
    actions: 0,
    move: 2.5,
    description:
      'SZF合成失败形态，自带冲锋。蓄力一回合后可连续移动5次、每次四向1格；可进入敌方随从格造成30伤害，无免费弹出，最终必须停在空地。',
  },
  {
    id: 'u13',
    tier: 'ultimate',
    name: '改判小法师',
    glyph: '改',
    role: '终极随从',
    attack: 10,
    health: 10,
    range: 1,
    actions: 1,
    move: 1,
    description:
      '每个实际己方回合每名法师各可改判一次，冲锋号令不会刷新次数。召唤次数用完后，可将本回合的一次召唤结果消除并从原卡池自动重抽，不额外扣费；克隆军团按完整一批替换。前五个己方回合内，自己被抽到时也可直接重抽自己一次；不连锁重复。',
    skill: '改判',
    mage: true,
  },
  {
    id: 'u14',
    tier: 'ultimate',
    name: '灵魂法师',
    glyph: '魂',
    role: '终极随从',
    attack: 0,
    health: 35,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '每回合一次免费选择射程内两个不同目标（含自己、双方、中立和基地），建立虹吸：回合结束第一目标−20、第二目标+20生命，最多3条。任一端离开施法者射程，整条连接立刻失效。',
    skill: '建立虹吸',
    mage: true,
  },
  {
    id: 'u15',
    tier: 'ultimate',
    name: '免疫塔',
    glyph: '佑',
    role: '终极随从',
    attack: 0,
    health: 60,
    range: 4,
    actions: 1,
    move: 0.5,
    description:
      '范围内友方可避免一次法术或敌方技能的效果。每次成功阻挡，塔生命上限−15；上限归零时离场。半速移动需要蓄力。',
  },
  {
    id: 'u16',
    tier: 'ultimate',
    name: '靴子',
    glyph: '靴',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '装备者完成移动后，可额外执行一次攻击操作，攻击次数仍按自身第四属性。一次移动操作只触发一次。',
    weapon: 8,
  },
  {
    id: 'u17',
    tier: 'ultimate',
    name: '冲锋号令',
    glyph: '号',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使一友方随从独立于战场提前进入自己的下回合：刷新操作，推进其独立效果时钟、部署疲劳与已存蓄力。不提前触发死吧！或策反，也不刷新改判次数；这些使用实际回合计时。储存限制8个己方回合，包含抽到的回合。',
    spell: 8,
  },
  {
    id: 'u18',
    tier: 'ultimate',
    name: '厚脸皮之王',
    glyph: '王',
    role: '终极随从',
    attack: 15,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '受到不超过10的攻击伤害时免疫。实际受到伤害后立即对伤害来源发动一次普通攻击，不占主动回合操作；反击仍需合法射程，连锁反击同一来源链不无限递归。',
  },
  {
    id: 'u19',
    tier: 'ultimate',
    name: '溟界小法师',
    glyph: '溟',
    role: '终极随从',
    attack: 0,
    health: 25,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '技能：在射程内合法空格，复活上一或上上己方回合窗口内死亡的友方，恢复刚召唤的初始形态，无装备和临时效果；自己生命上限−20，不足20也可发动，扣至0时完成复活后自身离场，不给敌方人头。复活不重新抽取变体判定，每条阵亡记录只可使用一次。',
    skill: '复活',
    mage: true,
  },
  {
    id: 'u20',
    tier: 'ultimate',
    name: '击退法师',
    glyph: '退',
    role: '终极随从',
    attack: 5,
    health: 55,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '攻击时可选择射程内合法路径的最后一步方向，命中后沿该方向击退2格。身后有1个单格单位则两者各推1格；2个单位或2×2单位阻挡时不推。两格空间不足且由边界阻挡时，受击者额外−30血。',
    skill: '击退被动',
    mage: true,
  },
  {
    id: 'u21',
    tier: 'ultimate',
    name: '超级奶妈',
    glyph: '慈',
    role: '终极随从',
    attack: 25,
    health: 35,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '攻击敌方造成25伤害，攻击友方改为治疗25。技能：射程内一友方下回合+10攻击。死亡时射程内所有友方回复25生命。',
    skill: '鼓舞单体',
  },
  {
    id: 'u22',
    tier: 'ultimate',
    name: '跑得快小屋',
    glyph: '屋',
    role: '终极随从',
    attack: 0,
    health: 50,
    range: 4,
    actions: 1,
    move: 0.5,
    description:
      '范围内友方死亡时，可在范围内合法空地召唤一只普通20，并扣自身10生命上限。每次死亡分别处理；无处放置或被沉默/冻结则不触发。',
    skill: '死亡召唤',
  },
  {
    id: 'u23',
    tier: 'ultimate',
    name: '超级钩子',
    glyph: '钩',
    role: '终极随从',
    attack: 30,
    health: 35,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '每次击杀后，下个己方回合可放弃攻击操作，将任意一名敌方随从移至自身正前方。前方按朝敌方基地方向计算；无合法完整落位则不可发动。',
    skill: '绝境牵引',
  },
  {
    id: 'u24',
    tier: 'ultimate',
    name: '寒冰塔',
    glyph: '寒',
    role: '终极随从',
    attack: 0,
    health: 81,
    range: 5,
    actions: 1,
    move: 0,
    description:
      '每回合选择自身11×11区域内一格标记；下个己方回合开始若该格有敌方随从，则冰冻2回合。本塔造成的冰冻，每回合结束额外扣5血（合计10）。',
    skill: '寒冰标记',
  },
  {
    id: 'u25',
    tier: 'ultimate',
    name: '克隆军团',
    glyph: '众',
    role: '终极随从',
    attack: 10,
    health: 10,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '一次终极召唤获得同批8枚，可叠放在友方克隆军团格上。范围法术命中所有叠放者，敌方单体攻击和技能只命中栈顶。整批最后一枚死亡才触发死亡被动和一颗人头；不可献祭。',
  },
  {
    id: 'u26',
    tier: 'ultimate',
    name: '心灵之火',
    glyph: '心',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使任一随从的攻击力始终等于它当前的生命值，随生命变化实时更新。可指定敌方；负面法术免疫仍可拦截。',
    spell: 6,
  },
  {
    id: 'u27',
    tier: 'ultimate',
    name: '矿工',
    glyph: '矿',
    role: '终极随从',
    attack: 30,
    health: 50,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '可在棋盘任何合法空地部署，不受部署行限制。部署后的第一个己方回合可选择两个操作，后续恢复一个；攻击基地只造成10伤害。',
  },
  {
    id: 'u28',
    tier: 'ultimate',
    name: '炎魔之心',
    glyph: '炎',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '非法师可装备，+5当前与最大生命，免疫冰冻。普通攻击改为沿选择的四向直线穿透射程内所有敌方随从并附加灼烧。具有冲锋的随从部署当回合不可装备。3张未装备的炎魔之心可合成炎魔之王。',
    weapon: 10,
  },
  {
    id: 'firelord',
    tier: 'derived',
    name: '炎魔之王',
    glyph: '烬',
    role: '合成',
    attack: 80,
    health: 80,
    range: 6,
    actions: 1,
    move: 0.5,
    description:
      '3张未装备炎魔之心在己方回合开始合成。不能主动攻击（沉默也不能）。每个己方回合结束，对以自身为中心13×13内当前生命最高的敌方造成80技能伤害，不受路径阻挡；命中格的敌方叠放者均受击，上下左右四格只对敌方溅射10，每单位一次。半速移动需蓄力。',
  },
];
// Synthesis results never enter either random summon pool.
CATALOG.push(
  {
    id: 'sage',
    tier: 'derived',
    name: '至圣先师',
    glyph: '师',
    role: '合成',
    attack: 25,
    health: 100,
    range: 5,
    actions: 2,
    move: 2,
    description:
      '3名超级奶妈合成。±25：攻击前可选择伤害或治疗，可攻击友方；友方被伤害攻击击杀时人头归己方。攻击范围内所有友方（含自身）获得+5攻击光环，可叠加，离开范围、沉默或冰冻即失效。亡语：全场友方棋子回满生命，不治疗基地。',
  },
  {
    id: 'formless',
    tier: 'derived',
    name: '无相勾',
    glyph: '相',
    role: '合成',
    attack: 10,
    health: 40,
    range: 100,
    actions: 0.5,
    move: 0.5,
    description:
      '3名超级钩子合成。无限射程但仍遵守攻击路径阻挡；攻击、移动均须先用一回合蓄力，下回合消耗对应1层执行一次。命中后可选择将该存活敌方棋子拉到身前合法完整落位，不额外消耗操作，不能拉基地。',
  },
  {
    id: 'slayer',
    tier: 'derived',
    name: '杀圣',
    glyph: '戮',
    role: '合成',
    attack: 10,
    health: 70,
    range: 6,
    actions: 2,
    move: 2,
    description:
      '3名精英杀手合成。攻击自带四向直线穿透，实际攻击伤害100%吸血；受到有随从来源的伤害时，将实际扣血的50%反弹给发出者（致死也生效）。反伤不再次反伤。不继承原精英杀手的暴击和击杀成长。',
  },
  {
    id: 'citadel',
    tier: 'derived',
    name: '跑得快王城',
    glyph: '城',
    role: '合成',
    attack: 15,
    health: 180,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '3座跑得快小屋合成。范围内每个友方棋子死亡时，必须扣10生命上限并在范围内选择合法位置召唤一只普通20超级跑得快；包括自己召唤的单位。每次死亡分别处理，不按克隆批次合并。无合法位置或上限不足10时不召唤、不扣费；恰好10时先召唤再离场。',
  },
  {
    id: 'archmage',
    tier: 'derived',
    name: '万法真君',
    glyph: '法',
    role: '合成',
    mage: true,
    attack: 30,
    health: 90,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '3名法术反制小法师合成。法师单位。敌方释放法术时有2/3概率反制，法术消耗但无效；成功时自身生命上限和当前生命各+15。多个反制来源按入场顺序独立尝试，首个成功后停止，只有成功来源成长。沉默或冰冻时不反制。',
  },
);
// 3.0: shrine identities stay outside both random summon pools.
export const SHRINE_POOL: Kind[] = Array.from({ length: 16 }, (_, i) => `s${i + 1}` as Kind);
export const FLAG_CELLS: Point[] = [
  { x: 7, y: 8 },
  { x: 7, y: 9 },
  { x: 7, y: 10 },
];
const shrine = (
  id: Kind,
  name: string,
  glyph: string,
  attack: number,
  health: number,
  range: number,
  actions: number,
  move: number,
  description: string,
  extra: Partial<Definition> = {},
): Definition => ({
  id,
  name,
  glyph,
  tier: 'shrine',
  role: '神龛随从',
  attack,
  health,
  range,
  actions,
  move,
  description,
  ...extra,
});
CATALOG.push(
  shrine(
    's1',
    '金晔',
    '晔',
    40,
    20,
    0,
    0,
    0,
    '地标，只能部署于开局公共三行。友方随从部署其上获得17冲锋号令；原本具有冲锋者本回合可执行两次完整操作。重建5个己方回合。地标每己方回合可主动攻击一次同格敌方，不能移动。',
    { role: '神龛地标', landmark: { rebuild: 5 } },
  ),
  shrine(
    's2',
    '铁吊',
    '铁',
    20,
    20,
    0,
    0,
    0,
    '武器：装备者+20攻击、+20当前及最大生命。装备者死亡后返回其所属方储存区。替换装备不算死亡。永久储存。',
    { role: '神龛武器', weapon: -1 },
  ),
  shrine(
    's3',
    'CX',
    'CX',
    5,
    55,
    6,
    1,
    1,
    '每次攻击依次独立判定：1/3概率策反命中的存活敌方非神龛棋子（攻击本身须造成正伤害）；1/4概率获得一次本回合额外召唤。神龛模式额外召唤使用终极池。',
  ),
  shrine(
    's4',
    '融合怪',
    '融',
    20,
    60,
    5,
    1,
    1,
    '±20：攻击前可选择造成伤害或治疗，可选择友方。友方被伤害攻击击杀时人头归己方。每个己方回合结束，攻击范围内友方棋子回满生命。',
    { signedAttack: true },
  ),
  shrine(
    's5',
    'ZF·强夺',
    '夺',
    20,
    55,
    5,
    1,
    1,
    '可攻击友方。击杀棋子后获得其武器和全部技能描述（不复制基础属性、身份或尺寸）。主动能力可分别选择，沉默会抑制所获技能。武器转移而非复制，延续单装备槽规则。',
  ),
  shrine(
    's6',
    'ZF·反射',
    '返',
    10,
    120,
    4,
    1,
    1,
    '±10：可选择攻击伤害或治疗，可被友方攻击。伤害攻击时另造成本回合与上回合累计实际所受伤害；不包括未扣血的免疫或溢出伤害。',
    { signedAttack: true },
  ),
  shrine(
    's7',
    'YYF',
    'YY',
    5,
    55,
    100,
    2,
    1,
    '无限攻击射程，仍遵守路径阻挡。不能装备任何武器，也不能接受友方单位提供的攻击力增益。该限制同样适用于所有模式的普通10投石机。',
  ),
  shrine(
    's8',
    '举旗',
    '旗',
    10,
    30,
    0,
    0,
    0,
    '地标，只能部署在(7,8)、(7,9)、(7,10)，此专属落点优先于通用公共三行限制。所有友方棋子+10攻击及当前/最大生命；失效时撤回攻击和生命上限，不扣当前生命。重建4个己方回合。每己方回合可主动攻击一次同格敌方。',
    { role: '神龛地标', landmark: { rebuild: 4, allowed: FLAG_CELLS } },
  ),
  shrine(
    's9',
    '玉碎',
    '碎',
    0,
    0,
    0,
    0,
    0,
    '永久光环。开局秘密选择奇数或偶数。相应编号的友方随从可选择自杀，消灭自己并对攻击范围内一个敌方造成(攻击+当前生命)/2、向上取整到5的倍数的伤害。自杀不产生人头。',
    { role: '神龛光环', aura: true },
  ),
  shrine(
    's10',
    '时钟',
    '时',
    0,
    0,
    0,
    0,
    0,
    '永久光环，每个实际己方回合一次。把存活的非神龛棋子恢复至上一个己方回合开始的状态，包括位置、生命、装备、效果、行动和技能次数；原位置被占时不能使用。没有旧快照的敌方新召唤棋子恢复为初始状态。不复活亡者，不复制已经转移的神龛武器。',
    { role: '神龛光环', aura: true },
  ),
  shrine(
    's11',
    '强杀',
    '杀',
    0,
    0,
    0,
    0,
    0,
    '永久光环。己方单位及法术造成的每份伤害+5，敌方棋子与基地不能被治疗。增加伤害不等于增加攻击力。',
    { role: '神龛光环', aura: true },
  ),
  shrine(
    's12',
    '先攻·ZP',
    '先',
    10,
    55,
    5,
    1,
    1,
    '每次普通攻击完成后独立判定，有3/5概率获得一次本回合额外完整操作，可继续攻击、移动或使用技能。',
  ),
  shrine(
    's13',
    '老千K',
    '千',
    0,
    0,
    0,
    0,
    0,
    '永久光环。每回合常驻两次召唤前独立判定：1/3概率抽4个结果，否则抽3个，再选两个。克隆整批算一个结果。人头召唤及其他额外召唤不受影响。',
    { role: '神龛光环', aura: true },
  ),
  shrine(
    's14',
    '法力之泉',
    '泉',
    -20,
    50,
    5,
    1,
    1,
    '法师。攻击恒为治疗20，可以指定友方或敌方，不受攻击增益影响。存活且技能有效时，己方伤害法术和法师的伤害技能每份伤害+15（多个来源叠加）。',
    { mage: true },
  ),
  shrine(
    's15',
    'BW之刃',
    '刃',
    20,
    -5,
    0,
    0,
    0,
    '武器：装备者+20攻击、-5生命上限。伤害攻击额外附带目标受击前已损生命值的伤害。装备期间击杀过敌方棋子后，装备者死亡时武器返回储存区；未击杀或被替换不返还。永久储存。',
    { role: '神龛武器', weapon: -1 },
  ),
  shrine(
    's16',
    '胡桃木手杖',
    '杖',
    0,
    0,
    1,
    0,
    0,
    '法师专用武器，+1攻击射程。被装备者攻击命中的棋子立即-15攻击（包括治疗攻击），持续到装备者下一个实际己方回合开始。永久储存。',
    { role: '神龛武器', weapon: -1 },
  ),
  shrine(
    'laoqian',
    '牢千K',
    '牢',
    0,
    0,
    0,
    0,
    0,
    '特殊合成光环：3名终极13改判小法师合成。永久存在，每个实际己方回合最多一次，把一次召唤改为从该来源池自选一个结果。适用于经典和神龛模式，不进入16神龛抽选池。',
    { role: '合成光环', aura: true },
  ),
);

export const LIBRARY = Object.fromEntries(CATALOG.map((d) => [String(d.id), d])) as Record<
  string,
  Definition
>;
export function definition(kind: Kind): Definition {
  const d = Object.hasOwn(LIBRARY, String(kind)) ? LIBRARY[String(kind)] : undefined;
  if (!d) throw new Error(`未知棋子：${kind}`);
  return d;
}
export const SUMMON_POOL: Kind[] = Array.from({ length: 26 }, (_, i) => i + 1);
export const ULTIMATE_POOL: Kind[] = Array.from({ length: 28 }, (_, i) => `u${i + 1}` as Kind);
export const isStored = (d: Definition) =>
  d.spell !== undefined || d.weapon !== undefined || !!d.aura || d.tier === 'shrine';
export const RULE_NOTES = [
  '作者已确认：四向曼哈顿距离；3′实时40−5n与射程n；期限按己方回合且包含抽到的回合；部署权限按回合开始快照；随机数随悔棋恢复。',
  '新版的第四属性是攻击次数。普通棋子每回合只能选择移动、攻击、技能、蓄力中的一种模式；选攻击后可连续攻击，不能把剩余攻击改为移动或技能。',
  '主动蓄力替代旧版定炮自动蓄力。回合开始已经持有的层数才能用于分数行为；名刀虽不能攻击，仍可蓄力移动。',
  '金身免疫伤害及一切敌方技能法术，包括死吧！与策反；不阻止己方的非伤害献祭。策反要求攻击本身造成正伤害，标记爆炸不算；策反后的下一己方回合可以行动。',
  '经典模式终极召唤在回合开始、看到该次结果之前支付2人头替换一次普通召唤。终极池28个编号等概率有放回。克隆一批8枚最后死亡才计算一颗人头。',
  '冰冻保留所有权记录用于回合计时、复原、死亡归属与人头判定，但攻击目标和阻挡视为中立。冰冻/眩晕持续期按被影响单位的己方回合；每回合末伤害按双方回合结束分别结算。',
  '武器采用一个装备槽；再次装备替换原武器，不返还旧武器牌。移除武器会撤销其数值，当前生命不超过新上限。此槽位数量为未注明项的暂定解释。',
  '持续法术与多目标技能先确定本次目标，再逐个结算。每个目标一次免疫塔判定，单次效果内被塔挡住的目标不重复消耗塔生命上限。',
  '末日守卫两个概率采用互斥区间。精英杀手暴击率最多100%，吸血可超过100%；第5个人头只加一次射程。',
  '炎魔之心穿透使用四向直线；炎魔之王最高血并列时按棋盘行列与生成顺序确定。伤害造成的连锁反击每条链防止同源无穷循环。',
  '作者补充确认：冲锋号令储存8个己方回合。3.0新增独立神龛模式及牢千K合成，合成结果不进入随机池；善铁仍暂缓。',
  '支持同屏双人与本地AI；神龛第0回合双方候选公开、选择与玉碎奇偶保密，双方锁定后共同揭示。尚未实现联机服务。',
  '神龛模式常驻两次免费终极召唤；回合开始可额外花3人头终极、2人头普通。地标独立占格层、摧毁后休眠重建；举旗专属(7,8)/(7,9)/(7,10)。',
  '牢千K每回合可将一次召唤改为自选来源池的一个编号；确定该编号本体，不再随机判定3′、17′或小BW。随机召唤的原概率不变。',
  '2.x存档继续读写原v2格式；神龛、光环、时钟与继承技能均为可选扩展。1.x旧规则存档仍不自动迁移。',
];
