import type { Definition, Kind } from './types';
/** Numeric combat parameters shared by resolution and read-only AI estimates. */
export const COMBAT_RULES = {
  charger: { heavyChance: 1 / 12, criticalChance: 1 / 3, heavyBonus: 60, bonus: 20 },
  superCritical: { lethalChance: 1 / 5, doubleChance: 1 / 3, lethalDamage: 100 },
  vampire: { base: 0.2, perKill: 0.2 },
  minerBaseDamage: 10,
  frontDamageCap: 10,
  kingAttackImmunity: 10,
  catapultMarkDamage: 5,
} as const;
/** Single source for both rule stats and the UI codex. Fractional attributes retain their exact numeric value. */
export const CATALOG: Definition[] = [
  {
    id: 1,
    tier: 'normal',
    name: '冲锋怪',
    glyph: '冲',
    role: '爆发',
    attack: 20,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '普通攻击：2/3概率造成20伤害，1/4概率造成40伤害，1/12概率造成80伤害。部署时可失去10点当前与最大生命，获得冲锋，当回合即可行动。',
  },
  {
    id: 2,
    tier: 'normal',
    name: '奶妈',
    glyph: '愈',
    role: '治疗',
    attack: 20,
    health: 30,
    range: 2,
    actions: 1,
    move: 1,
    description:
      '攻击友方随从时改为治疗20点，不超过生命上限。死亡后，由所属玩家选择一次无视距离的攻击或治疗；也可以放弃。',
  },
  {
    id: 3,
    tier: 'normal',
    name: '名刀',
    glyph: '佑',
    role: '守护',
    attack: 0,
    health: 60,
    range: 6,
    actions: 0,
    move: 0.5,
    description:
      '抽到时1/3为名刀，否则为残影。范围内友方（含自身）一生避免一次致命伤害并以1血存活。攻击次数为0不妨碍移动：选择蓄力回合后，下一回合可消耗1层移动一格。',
  },
  {
    id: '3p',
    tier: 'derived',
    name: '名刀·残影',
    glyph: '影',
    role: '异变',
    attack: 40,
    health: 25,
    range: 1,
    actions: 1,
    move: 1,
    description:
      '攻击力=max(0,40−5n)，射程=n。n为以自身为中心3×3区域内的随从数量，包含双方、自身与衍生物；大体型只计一个。',
  },
  {
    id: 4,
    tier: 'normal',
    name: '定炮',
    glyph: '炮',
    role: '重炮',
    attack: 100,
    health: 40,
    range: 4,
    actions: 0.3333333333333333,
    move: 1,
    description:
      '不能直接攻击。主动选择蓄力作为本回合操作；回合开始已有至少2层时可攻击，开炮消耗全部层数。5层开炮射程+1；移动保留蓄力，移动回合不会自动增加层数。',
  },
  {
    id: 5,
    tier: 'normal',
    name: '大肉比',
    glyph: '岳',
    role: '重装',
    attack: 15,
    health: 111,
    range: 2,
    actions: 1,
    move: 0.5,
    description:
      '占2×2格。选择移动蓄力后，下一回合可消耗1层整体移动一格。技能：对体型外围一圈12格（含四个对角）内的目标造成20伤害，包含友方，每单位只结算一次。',
    skill: '震地',
    size: 2,
  },
  {
    id: 6,
    tier: 'normal',
    name: 'BUFF怪',
    glyph: '振',
    role: '辅助',
    attack: 20,
    health: 20,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '技能使当前攻击范围内的所有友方随从在下个己方回合攻击+10，对投石机无效；不同施放可以叠加。',
    skill: '鼓舞',
  },
  {
    id: 7,
    tier: 'normal',
    name: '钩子',
    glyph: '钩',
    role: '控制',
    attack: 30,
    health: 55,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '选择射程内的敌方随从，将其移到你的射程内另一合法空位。不能钩基地；大体型须完整放得下。',
    skill: '牵引',
  },
  {
    id: 8,
    tier: 'normal',
    name: '爆弹',
    glyph: '爆',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '选择一个完整2×2区域，对其中所有目标造成20伤害，包括双方随从与基地。每个大体型随从只受伤一次。',
    spell: 4,
  },
  {
    id: 9,
    tier: 'normal',
    name: '射手',
    glyph: '弓',
    role: '连击',
    attack: 10,
    health: 45,
    range: 5,
    actions: 2,
    move: 1,
    description: '选择攻击操作后可攻击两次，目标必须不同。不能把第二次攻击改为移动或技能。',
  },
  {
    id: 10,
    tier: 'normal',
    name: '投石机',
    glyph: '印',
    role: '标记',
    attack: 0,
    health: 20,
    range: 100,
    actions: 2,
    move: 1,
    description:
      '命中敌方目标后施加一轮标记。目标满血时立即触发，或再次被同阵营的非投石机随从命中时触发，额外造成5伤害。标记触发即移除，同阵营标记不叠加。基地也使用同样的标记规则。',
  },
  {
    id: 11,
    tier: 'normal',
    name: '白嫖怪',
    glyph: '召',
    role: '遗赠',
    attack: 20,
    health: 20,
    range: 4,
    actions: 1,
    move: 1,
    description: '死亡后，下个己方回合额外召唤一次；多个白嫖怪的效果可累加。',
  },
  {
    id: 12,
    tier: 'normal',
    name: '跑得快',
    glyph: '疾',
    role: '游击',
    attack: 5,
    health: 1,
    range: 6,
    actions: 2,
    move: 2,
    description:
      '与敌方随从四向相邻时，攻击次数与移动距离各−1。攻击模式不可改为移动模式。死亡后在原地留下0/70/0/0/0的己方墓地。',
  },
  {
    id: 13,
    tier: 'normal',
    name: '直行侠',
    glyph: '驰',
    role: '突进',
    attack: 25,
    health: 35,
    range: 4,
    actions: 1,
    move: 3,
    description: '移动必须恰好三格，且只能沿同一行或同一列直线前进，途中不能穿过任何单位或基地。',
  },
  {
    id: 14,
    tier: 'normal',
    name: '献祭炮',
    glyph: '祭',
    role: '献祭',
    attack: 0,
    health: 30,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '自身生命上限−10，当前生命不超过新上限。消灭范围内另一友方随从，再选择一列，沿进攻方向对射程内该列第一个敌方造成被献祭者的当前攻击力伤害。',
    skill: '献祭射击',
  },
  {
    id: 15,
    tier: 'normal',
    name: '蓄力怪',
    glyph: '炼',
    role: '成长',
    attack: 5,
    health: 30,
    range: 2,
    actions: 2,
    move: 1,
    description:
      '技能：永久+10攻击或+1射程，一生最多强化3次。技能占本回合唯一操作；第四属性2代表选择攻击时能攻击两次，不代表可以强化两次。',
    skill: '自我强化',
  },
  {
    id: 16,
    tier: 'normal',
    name: '伤害转化器',
    glyph: '镜',
    role: '转化',
    attack: 5,
    health: 100,
    range: 2,
    actions: 1,
    move: 1,
    description:
      '可被友方随从攻击。实际受到友方伤害后，可选择射程内一个敌方目标造成等量伤害；也可放弃。过量伤害只按实际扣血计。',
  },
  {
    id: 17,
    tier: 'normal',
    name: '金身',
    glyph: '御',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使一个友方直到其下回合开始免疫所有伤害与所有敌方技能、法术，包括死吧！和策反。己方献祭等非伤害效果不受阻止。',
    spell: 100,
  },
  {
    id: 18,
    tier: 'normal',
    name: '死吧！',
    glyph: '灭',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使一友方下个回合命中的首个敌方随从立即死亡。不能处决基地；金身可免疫。效果只在该下回合有效。',
    spell: 7,
  },
  {
    id: 19,
    tier: 'normal',
    name: '路障小法师',
    glyph: '障',
    role: '召唤',
    attack: 20,
    health: 30,
    range: 4,
    actions: 1,
    move: 1,
    description: '在攻击范围内的合法空位生成0/50/0/0/0的己方路障。路障于你下个回合开始消失。',
    skill: '制造路障',
    mage: true,
  },
  {
    id: 20,
    tier: 'normal',
    name: '超级跑得快',
    glyph: '迅',
    role: '反击',
    attack: 20,
    health: 20,
    range: 2,
    actions: 2,
    move: 2,
    description:
      '20/20/2/2/2。死亡判定：1/2概率敌方不能获得这颗人头；否则对伤害来源造成30伤害。无随从伤害来源时不会虚构反击目标。',
  },
  {
    id: 21,
    tier: 'normal',
    name: '神行千里',
    glyph: '跃',
    role: '蓄势',
    attack: 30,
    health: 35,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '主动选择技能蓄力，在两个回合各积累1层；第三回合可扣10血，移动最多6格并攻击一次。移动不清除蓄力；发动需至少保留1血。',
    skill: '神行突袭',
  },
  {
    id: 22,
    tier: 'normal',
    name: '策反',
    glyph: '易',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使一友方下回合首次对敌方随从造成伤害时，将存活目标变为友方。金身免疫；不能作用基地。新友方本回合疲劳，下一个己方回合即可行动（独行侠也不额外多休息）。',
    spell: 3,
  },
  {
    id: 23,
    tier: 'normal',
    name: '独行侠',
    glyph: '孤',
    role: '爆发',
    attack: 5,
    health: 30,
    range: 5,
    actions: 6,
    move: 1,
    description:
      '部署后第二个己方回合首次行动，此后隔回合行动。选择攻击可攻击6次，但不能混用移动。周围八格不可部署或移动友方。',
  },
  {
    id: 24,
    tier: 'normal',
    name: '厚脸皮',
    glyph: '盾',
    role: '防御',
    attack: 10,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '从正面进入的攻击伤害单次最多10。正面指攻击路径最后一步朝向自己的基地。最短合法路径并列时，有正面路线就按正面处理。无方向法术与反伤不受此限制。',
  },
  {
    id: 25,
    tier: 'normal',
    name: '重铸',
    glyph: '铸',
    role: '法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '立即额外召唤一次；或消灭两个当前生命不少于各自一半生命上限的友方随从，额外召唤两次。新随从仍必须当回合部署。',
    spell: 7,
  },
  {
    id: 26,
    tier: 'normal',
    name: '杀手',
    glyph: '刃',
    role: '收割',
    attack: 20,
    health: 45,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '每击杀一个敌方随从依次升级：①生命上限+10并治疗10；②攻击+5；③射程+1；然后循环。包括敌方墓地与路障。',
  },
  {
    id: 'grave',
    tier: 'derived',
    name: '墓地',
    glyph: '冢',
    role: '衍生物',
    attack: 0,
    health: 70,
    range: 0,
    actions: 0,
    move: 0,
    description: '跑得快的死亡遗留物。可被攻击、治疗、献祭、策反，也参与行控制权与残影人数计算。',
  },
  {
    id: 'wall',
    tier: 'derived',
    name: '路障',
    glyph: '垒',
    role: '衍生物',
    attack: 0,
    health: 50,
    range: 0,
    actions: 0,
    move: 0,
    description: '路障小法师创造的临时单位，在召唤者的下个己方回合开始消失。',
  },
  {
    id: 'u1',
    tier: 'ultimate',
    name: '末日守卫',
    glyph: '劫',
    role: '终极随从',
    attack: 30,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '自带冲锋。普通攻击1/3概率伤害翻倍，1/5概率伤害为100；采用互斥区间，余下7/15为普通伤害。',
  },
  {
    id: 'u2',
    tier: 'ultimate',
    name: '超级蓄力怪',
    glyph: '蓄',
    role: '终极随从',
    attack: 15,
    health: 65,
    range: 4,
    actions: 1,
    move: 1,
    description: '可选择攻击蓄力，每层+15攻击，最多4层。移动不消耗层数；一次攻击后清空蓄力。',
  },
  {
    id: 'u3',
    tier: 'ultimate',
    name: '法术反制小法师',
    glyph: '断',
    role: '终极随从',
    attack: 30,
    health: 30,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '对手释放法术时，每个未被沉默、未被冻结的反制小法师独立进行1/3反制判定，成功则法术无效但消耗法术牌。按文档的法师名单，本棋子不属于寒冰法杖适用的法师。',
  },
  {
    id: 'u4',
    tier: 'ultimate',
    name: '破法者',
    glyph: '禁',
    role: '终极随从',
    attack: 10,
    health: 50,
    range: 4,
    actions: 1,
    move: 2,
    description:
      '攻击命中敌方随从后，使其眩晕一回合并永久移除原有描述、被动与技能（沉默）。基础五项数值和装备保留；金身或免疫塔可拦截负面技能。',
  },
  {
    id: 'u5',
    tier: 'ultimate',
    name: '寒冰法杖',
    glyph: '冰',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '法师专用，装备后射程+1。攻击命中敌方随从后冰冻两回合：不能行动，每回合结束扣5血，对双方视作中立，双方攻击都被其阻挡也都能攻击它。法师名单：普通19，终极6、13、14、19、20。',
    weapon: 15,
  },
  {
    id: 'u6',
    tier: 'ultimate',
    name: '大法师',
    glyph: '法',
    role: '终极随从',
    attack: 0,
    health: 45,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '攻击附加持续6回合的灼烧，每回合结束扣5血；装备寒冰法杖后不再灼烧，基础攻击改为10。技能先蓄力一回合，后续可在自身11×11区域选择行列交点，十字各20伤害、中心40，整局只可发动一次。',
    skill: '十字浩劫',
    mage: true,
  },
  {
    id: 'u7',
    tier: 'ultimate',
    name: '超级BW',
    glyph: '岳',
    role: '终极随从',
    attack: 20,
    health: 90,
    range: 3,
    actions: 1,
    move: 0.5,
    description:
      '占2×2格，半速移动须蓄力。每生一次免费能力：自身攻击与当前生命各−10，使另一友方生命上限/当前生命+5并变为2×2。必须有完整合法落位。',
    skill: '巨大化',
    size: 2,
  },
  {
    id: 'u8',
    tier: 'ultimate',
    name: '精英杀手',
    glyph: '噬',
    role: '终极随从',
    attack: 10,
    health: 50,
    range: 4,
    actions: 2,
    move: 2,
    description:
      '20%吸血，攻击20%概率暴击×2。每击杀敌方吸血率与暴击率各+20%；暴击率最多100%，吸血率可超过100%。第五次击杀时射程+1（仅一次）。',
  },
  {
    id: 'u9',
    tier: 'ultimate',
    name: '烈焰风暴',
    glyph: '焰',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '选择任一完整横排或竖排，立即对所有目标造成20伤害；下个己方回合开始对同一行/列再造成20伤害，按当时占位重新判定。',
    spell: 6,
  },
  {
    id: 'u10',
    tier: 'ultimate',
    name: '厚脸皮暴怒者',
    glyph: '怒',
    role: '终极随从',
    attack: 5,
    health: 110,
    range: 4,
    actions: 1,
    move: 1,
    description: '每实际受到一次任意来源的正数伤害，永久+15攻击。免疫伤害不触发。',
  },
  {
    id: 'u11',
    tier: 'ultimate',
    name: '弑君',
    glyph: '弑',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '装备者+5攻击、+25生命上限（不立即治疗）。每个己方回合第一次攻击造成的实际伤害获得100%吸血。',
    weapon: 8,
  },
  {
    id: 'u12',
    tier: 'ultimate',
    name: 'SZF',
    glyph: '弹',
    role: '终极随从',
    attack: 0,
    health: 80,
    range: 0,
    actions: 0,
    move: 2.5,
    description:
      '抽到时1/10合成成功，否则为小BW。冲锋。先蓄力一回合，下回合可移动5次、每次四向1格。进入敌方/基地格造成30伤害后，必须选择方向弹出1格；若继续碰敌方则再伤害并继续弹出，弹出不消耗移动次数。',
  },
  {
    id: 'u12p',
    tier: 'derived',
    name: '小BW',
    glyph: '滚',
    role: '终极随从',
    attack: 0,
    health: 100,
    range: 0,
    actions: 0,
    move: 2.5,
    description:
      'SZF合成失败形态，自带冲锋。蓄力一回合后可连续移动5次、每次四向1格；可进入敌方随从格造成30伤害，无免费弹出，最终必须停在空地。',
  },
  {
    id: 'u13',
    tier: 'ultimate',
    name: '改判小法师',
    glyph: '改',
    role: '终极随从',
    attack: 10,
    health: 10,
    range: 1,
    actions: 1,
    move: 1,
    description:
      '每回合一次，可将本次召唤的一张牌重新抽取，保留原召唤池。前五个己方回合内，自己被抽到时也可直接重抽自己一次；不连锁重复。',
    skill: '改判',
    mage: true,
  },
  {
    id: 'u14',
    tier: 'ultimate',
    name: '灵魂法师',
    glyph: '魂',
    role: '终极随从',
    attack: 0,
    health: 35,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '每回合一次免费选择射程内两个不同目标（含自己、双方、中立和基地），建立虹吸：回合结束第一目标−20、第二目标+20生命，最多3条。任一端离开施法者射程，整条连接立刻失效。',
    skill: '建立虹吸',
    mage: true,
  },
  {
    id: 'u15',
    tier: 'ultimate',
    name: '免疫塔',
    glyph: '佑',
    role: '终极随从',
    attack: 0,
    health: 60,
    range: 4,
    actions: 1,
    move: 0.5,
    description:
      '范围内友方可避免一次法术或敌方技能的效果。每次成功阻挡，塔生命上限−15；上限归零时离场。半速移动需要蓄力。',
  },
  {
    id: 'u16',
    tier: 'ultimate',
    name: '靴子',
    glyph: '靴',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '装备者完成移动后，可额外执行一次攻击操作，攻击次数仍按自身第四属性。一次移动操作只触发一次。',
    weapon: 8,
  },
  {
    id: 'u17',
    tier: 'ultimate',
    name: '冲锋号令',
    glyph: '号',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使一友方随从独立于战场提前进入自己的下回合：刷新操作，推进其效果时钟、部署疲劳和已预约的死吧！等效果。储存限制8个己方回合，包含抽到的回合。',
    spell: 8,
  },
  {
    id: 'u18',
    tier: 'ultimate',
    name: '厚脸皮之王',
    glyph: '王',
    role: '终极随从',
    attack: 15,
    health: 50,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '受到不超过10的攻击伤害时免疫。实际受到伤害后立即对伤害来源发动一次普通攻击，不占主动回合操作；反击仍需合法射程，连锁反击同一来源链不无限递归。',
  },
  {
    id: 'u19',
    tier: 'ultimate',
    name: '溟界小法师',
    glyph: '溟',
    role: '终极随从',
    attack: 0,
    health: 25,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '技能：在射程内合法空格，复活上一或上上己方回合窗口内死亡的友方，恢复刚召唤的初始形态，无装备和临时效果；自己生命上限−20。复活不重新抽取变体判定，每条阵亡记录只可使用一次。',
    skill: '复活',
    mage: true,
  },
  {
    id: 'u20',
    tier: 'ultimate',
    name: '击退法师',
    glyph: '退',
    role: '终极随从',
    attack: 5,
    health: 55,
    range: 5,
    actions: 1,
    move: 1,
    description:
      '命中后沿攻击路径最后一步方向击退2格。身后有1个单格单位则两者各推1格；2个单位或2×2单位阻挡时不推。两格空间不足且由边界阻挡时，受击者额外−30血。',
    skill: '击退被动',
    mage: true,
  },
  {
    id: 'u21',
    tier: 'ultimate',
    name: '超级奶妈',
    glyph: '慈',
    role: '终极随从',
    attack: 25,
    health: 35,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '攻击敌方造成25伤害，攻击友方改为治疗25。技能：射程内一友方下回合+10攻击。死亡时射程内所有友方回复25生命。',
    skill: '鼓舞单体',
  },
  {
    id: 'u22',
    tier: 'ultimate',
    name: '跑得快小屋',
    glyph: '屋',
    role: '终极随从',
    attack: 0,
    health: 50,
    range: 4,
    actions: 1,
    move: 0.5,
    description:
      '范围内友方死亡时，可在范围内合法空地召唤一只普通20，并扣自身10生命上限。每次死亡分别处理；无处放置或被沉默/冻结则不触发。',
    skill: '死亡召唤',
  },
  {
    id: 'u23',
    tier: 'ultimate',
    name: '超级钩子',
    glyph: '钩',
    role: '终极随从',
    attack: 30,
    health: 35,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '每次击杀后，下个己方回合可放弃攻击操作，将任意一名敌方随从移至自身正前方。前方按朝敌方基地方向计算；无合法完整落位则不可发动。',
    skill: '绝境牵引',
  },
  {
    id: 'u24',
    tier: 'ultimate',
    name: '寒冰塔',
    glyph: '寒',
    role: '终极随从',
    attack: 0,
    health: 81,
    range: 5,
    actions: 1,
    move: 0,
    description:
      '每回合选择自身11×11区域内一格标记；下个己方回合开始若该格有敌方随从，则冰冻2回合。本塔造成的冰冻，每回合结束额外扣5血（合计10）。',
    skill: '寒冰标记',
  },
  {
    id: 'u25',
    tier: 'ultimate',
    name: '克隆军团',
    glyph: '众',
    role: '终极随从',
    attack: 10,
    health: 10,
    range: 4,
    actions: 1,
    move: 1,
    description:
      '一次终极召唤获得同批8枚，可叠放在友方克隆军团格上。范围法术命中所有叠放者，敌方单体攻击和技能只命中栈顶。整批最后一枚死亡才触发死亡被动和一颗人头；不可献祭。',
  },
  {
    id: 'u26',
    tier: 'ultimate',
    name: '心灵之火',
    glyph: '心',
    role: '终极法术',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '使任一随从的攻击力始终等于它当前的生命值，随生命变化实时更新。可指定敌方；负面法术免疫仍可拦截。',
    spell: 6,
  },
  {
    id: 'u27',
    tier: 'ultimate',
    name: '矿工',
    glyph: '矿',
    role: '终极随从',
    attack: 30,
    health: 50,
    range: 3,
    actions: 1,
    move: 1,
    description:
      '可在棋盘任何合法空地部署，不受部署行限制。部署后的第一个己方回合可选择两个操作，后续恢复一个；攻击基地只造成10伤害。',
  },
  {
    id: 'u28',
    tier: 'ultimate',
    name: '炎魔之心',
    glyph: '炎',
    role: '武器',
    attack: 0,
    health: 0,
    range: 0,
    actions: 0,
    move: 0,
    description:
      '非法师可装备，+5当前与最大生命，免疫冰冻。普通攻击改为沿选择的四向直线穿透射程内所有敌方随从并附加灼烧。具有冲锋的随从部署当回合不可装备。3张未装备的炎魔之心可合成炎魔之王。',
    weapon: 10,
  },
  {
    id: 'firelord',
    tier: 'derived',
    name: '炎魔之王',
    glyph: '烬',
    role: '合成',
    attack: 80,
    health: 80,
    range: 4,
    actions: 1,
    move: 0.5,
    description:
      '不能普通攻击。每个回合结束，对射程内生命最高的敌方造成80伤害，同格叠放者均受击，外围一圈溅射10伤害。半速移动需要蓄力。',
  },
];
export const LIBRARY = Object.fromEntries(CATALOG.map((d) => [String(d.id), d])) as Record<
  string,
  Definition
>;
export function definition(kind: Kind): Definition {
  const d = Object.hasOwn(LIBRARY, String(kind)) ? LIBRARY[String(kind)] : undefined;
  if (!d) throw new Error(`未知棋子：${kind}`);
  return d;
}
export const SUMMON_POOL: Kind[] = Array.from({ length: 26 }, (_, i) => i + 1);
export const ULTIMATE_POOL: Kind[] = Array.from({ length: 28 }, (_, i) => `u${i + 1}` as Kind);
export const isStored = (d: Definition) => d.spell !== undefined || d.weapon !== undefined;
export const RULE_NOTES = [
  '作者已确认：四向曼哈顿距离；3′实时40−5n与射程n；期限按己方回合且包含抽到的回合；部署权限按回合开始快照；随机数随悔棋恢复。',
  '新版的第四属性是攻击次数。普通棋子每回合只能选择移动、攻击、技能、蓄力中的一种模式；选攻击后可连续攻击，不能把剩余攻击改为移动或技能。',
  '主动蓄力替代旧版定炮自动蓄力。回合开始已经持有的层数才能用于分数行为；名刀虽不能攻击，仍可蓄力移动。',
  '金身免疫伤害及一切敌方技能法术，包括死吧！与策反；不阻止己方的非伤害献祭。策反后的下一己方回合可以行动。',
  '终极召唤在回合开始、看到该次结果之前支付2人头替换一次普通召唤。终极池28个编号等概率有放回。克隆一批8枚最后死亡才计算一颗人头。',
  '冰冻保留所有权记录用于回合计时、复原、死亡归属与人头判定，但攻击目标和阻挡视为中立。冰冻/眩晕持续期按被影响单位的己方回合；每回合末伤害按双方回合结束分别结算。',
  '武器采用一个装备槽；再次装备替换原武器，不返还旧武器牌。移除武器会撤销其数值，当前生命不超过新上限。此槽位数量为未注明项的暂定解释。',
  '持续法术与多目标技能先确定本次目标，再逐个结算。每个目标一次免疫塔判定，单次效果内被塔挡住的目标不重复消耗塔生命上限。',
  '末日守卫两个概率采用互斥区间。精英杀手暴击率最多100%，吸血可超过100%；第5个人头只加一次射程。',
  '炎魔之心穿透使用四向直线；炎魔之王最高血并列时按棋盘行列与生成顺序确定。伤害造成的连锁反击每条链防止同源无穷循环。',
  '作者补充确认：冲锋号令储存8个己方回合。善铁及相关合成属于尚未完成的3.0神龛模式，暂缓，不进入2.x规则、图鉴或召唤池。',
  '正式对局为同屏双人，双方手牌公开。老版存档不自动迁移到新版规则，避免静默改变正在进行的旧棋局。',
];
