import type { Difficulty } from './types';
export const DIFFICULTIES = {
  easy: {
    label: '简单',
    width: 1,
    depth: 1,
    perAction: 3,
    partial: 4,
    chanceSamples: 2,
    chanceLimit: 8,
    nodes: 100,
    turnNodes: 1200,
    turnMs: 500,
    decisionMs: 160,
    replyRoots: 0,
    noise: 10,
  },
  medium: {
    label: '中等',
    width: 2,
    depth: 5,
    perAction: 5,
    partial: 6,
    chanceSamples: 3,
    chanceLimit: 12,
    nodes: 320,
    turnNodes: 3200,
    turnMs: 1500,
    decisionMs: 450,
    replyRoots: 0,
    noise: 0,
  },
  hard: {
    label: '困难',
    width: 2,
    depth: 7,
    perAction: 4,
    partial: 5,
    chanceSamples: 4,
    chanceLimit: 18,
    nodes: 800,
    turnNodes: 8000,
    turnMs: 3500,
    decisionMs: 1000,
    replyRoots: 2,
    noise: 0,
  },
} as const;
export const difficultyLabel = (d: Difficulty) => DIFFICULTIES[d].label;
