import type { Difficulty } from './types';
export const DIFFICULTIES = {
  easy: {
    label: '简单',
    width: 1,
    depth: 1,
    perAction: 3,
    partial: 4,
    chanceSamples: 2,
    chanceLimit: 8,
    nodes: 400,
    turnNodes: 3500,
    turnMs: 500,
    decisionMs: 160,
    replyRoots: 0,
    noise: 10,
  },
  medium: {
    label: '中等',
    width: 8,
    depth: 5,
    perAction: 5,
    partial: 6,
    chanceSamples: 3,
    chanceLimit: 12,
    nodes: 1800,
    turnNodes: 10000,
    turnMs: 1500,
    decisionMs: 450,
    replyRoots: 0,
    noise: 0,
  },
  hard: {
    label: '困难',
    width: 24,
    depth: 9,
    perAction: 8,
    partial: 9,
    chanceSamples: 4,
    chanceLimit: 18,
    nodes: 5500,
    turnNodes: 30000,
    turnMs: 3500,
    decisionMs: 1000,
    replyRoots: 4,
    noise: 0,
  },
} as const;
export const difficultyLabel = (d: Difficulty) => DIFFICULTIES[d].label;
